### ISSUE TITLE
Cannot press scan button on fragment change

### ISSUE THREAD

**Issue by ZacharyLain** [clairepielak/FridgeBuddy#3]
When you move fragments and come back to home you cannot re-enter the scan now button.

**Comment by savannahmoss** [comment]
While I was working on coding the AddItem button, I found that if you move the button functionality to HomeFragment.java instead of having it rest within MainActivity.java, it removes the issue where if you move to another fragment and return to the home page the button loses its functionality. If there is a way to move the barcode scanner function to the HomeFragment I believe the issue will be fixed.

**Comment by ZacharyLain** [comment]
Moved the scan function to a utility file so it can now be used anywhere in the app. Should fix the issue.

**Comment by ZacharyLain** [comment]
Utility file functions can now be called anywhere by instantiating a class and then using the available functions in that class.
